---
- name: Ensure required dependencies are present.
  apt:
    name:
      - apt-transport-https
      - gnupg2
    state: present

- name: Add Filebeat repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/deb [trusted=yes] https://mirror.yandex.ru/mirrors/elastic/{{ filebeat_version }}/ stable main'
    state: present
    update_cache: true
